# Generated by Django 3.0.8 on 2020-07-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_album_name', models.CharField(max_length=256)),
                ('photo_album_alias_name', models.CharField(max_length=256)),
                ('photo_album_Introduction', models.CharField(max_length=256)),
            ],
        ),
    ]
